export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const ADD_CART_PRODUCTS = "ADD_CART_PRODUCTS";
export const GET_CART_PRODUCTS = "GET_CART_PRODUCTS";
export const POST_CART_PRODUCTS = "POST_CART_PRODUCTS";
